package com.tabesto.printer.model.error

import com.epson.epos2.Epos2Exception
import com.tabesto.printer.utils.Constants.PRINTER_ERR_UNKNOWN

@Suppress("unused")
enum class EposException(val codeInt: Int, val codeString: String) {
    EPOS_EXCEPTION_ERR_UNKNOWN(PRINTER_ERR_UNKNOWN, "ERR_UNKNOWN"),
    EPOS_EXCEPTION_ERR_ILLEGAL(Epos2Exception.ERR_ILLEGAL, "ERR_ILLEGAL"),
    EPOS_EXCEPTION_ERR_PARAM(Epos2Exception.ERR_PARAM, "ERR_PARAM"),
    EPOS_EXCEPTION_ERR_CONNECT(Epos2Exception.ERR_CONNECT, "ERR_CONNECT"),
    EPOS_EXCEPTION_ERR_TIMEOUT(Epos2Exception.ERR_TIMEOUT, "ERR_TIMEOUT"),
    EPOS_EXCEPTION_ERR_MEMORY(Epos2Exception.ERR_MEMORY, "ERR_MEMORY"),
    EPOS_EXCEPTION_ERR_PROCESSING(Epos2Exception.ERR_PROCESSING, "ERR_PROCESSING"),
    EPOS_EXCEPTION_ERR_NOT_FOUND(Epos2Exception.ERR_NOT_FOUND, "ERR_NOT_FOUND"),
    EPOS_EXCEPTION_ERR_IN_USE(Epos2Exception.ERR_IN_USE, "ERR_IN_USE"),
    EPOS_EXCEPTION_ERR_TYPE_INVALID(Epos2Exception.ERR_TYPE_INVALID, "ERR_TYPE_INVALID"),
    EPOS_EXCEPTION_ERR_DISCONNECT(Epos2Exception.ERR_DISCONNECT, "ERR_DISCONNECT"),
    EPOS_EXCEPTION_ERR_ALREADY_OPENED(Epos2Exception.ERR_ALREADY_OPENED, "ERR_ALREADY_OPENED"),
    EPOS_EXCEPTION_ERR_ALREADY_USED(Epos2Exception.ERR_ALREADY_USED, "ERR_ALREADY_USED"),
    EPOS_EXCEPTION_ERR_BOX_COUNT_OVER(Epos2Exception.ERR_BOX_COUNT_OVER, "ERR_BOX_COUNT_OVER"),
    EPOS_EXCEPTION_ERR_BOX_CLIENT_OVER(Epos2Exception.ERR_BOX_CLIENT_OVER, "ERR_BOX_CLIENT_OVER"),
    EPOS_EXCEPTION_ERR_UNSUPPORTED(Epos2Exception.ERR_UNSUPPORTED, "ERR_UNSUPPORTED"),
    EPOS_EXCEPTION_ERR_FAILURE(Epos2Exception.ERR_FAILURE, "ERR_FAILURE"),
}
